# Generated by Django 3.1.5 on 2021-01-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='link',
        ),
    ]
